#---------------------------------#
#      general configuration      #
#---------------------------------#

# Maximum number of concurrent jobs for the project
max_jobs: 2

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  nodejs_version: "6"

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - dotnet --info

build_script:
  - dotnet test ./TSQLLint.Tests/TSQLLint.Tests.csproj

after_test:
  - cmd: ./scripts/cover.cmd
  - cmd: 7z a coverage.zip %APPVEYOR_BUILD_FOLDER%\coverage
  - cmd: ./scripts/publish/publish.cmd
  - cmd: ./scripts/packageRuntimes/packageRuntimes.cmd
  - cmd: npm pack

before_deploy:
  - cmd: ./scripts/publish/publish.cmd
  - cmd: ./scripts/packageRuntimes/packageRuntimes.cmd
  - cmd: npm pack

deploy:
  provider: GitHub
  auth_token:
    secure: +ldQnV1tY0iQRt0oAaumSoPCc7J2VWvS5wnnCx8blmwsnKPWzqO9uHvZ+cRKBjAP
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true

artifacts:
  - path: /**\.tgz/
  - path: coverage.zip  
